sonarr:
  shows:
    base_url: !secret sonarr_base_url
    api_key: !secret sonarr_api_key

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-custom-formats-web-2160p
