services:
  # ______                  _
  # | ___ \                | |
  # | |_/ / __ _____      _| | __ _ _ __ _ __
  # |  __/ '__/ _ \ \ /\ / / |/ _` | '__| '__|
  # | |  | | | (_) \ V  V /| | (_| | |  | |
  # \_|  |_|  \___/ \_/\_/ |_|\__,_|_|  |_|
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # ______          _
  # | ___ \        | |
  # | |_/ /__ _  __| | __ _ _ __ _ __
  # |    // _` |/ _` |/ _` | '__| '__|
  # | |\ \ (_| | (_| | (_| | |  | |
  # \_| \_\__,_|\__,_|\__,_|_|  |_|
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./appdata/radarr:/config
      - /mnt/hdd/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped

  #  _____
  # /  ___|
  # \ `--.  ___  _ __   __ _ _ __ _ __
  #  `--. \/ _ \| '_ \ / _` | '__| '__|
  # /\__/ / (_) | | | | (_| | |  | |
  # \____/ \___/|_| |_|\__,_|_|  |_|
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./appdata/sonarr:/config
      - /mnt/hdd/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    restart: unless-stopped

  # ______                     _
  # | ___ \                   | |
  # | |_/ /___  ___ _   _  ___| | __ _ _ __ _ __
  # |    // _ \/ __| | | |/ __| |/ _` | '__| '__|
  # | |\ \  __/ (__| |_| | (__| | (_| | |  | |
  # \_| \_\___|\___|\__, |\___|_|\__,_|_|  |_|
  #                  __/ |
  #                 |___/
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    user: 1000:1000
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./appdata/recyclarr:/config

  #  _____ _            _
  # |  __ \ |          | |
  # | |  \/ |_   _  ___| |_ _   _ _ __
  # | | __| | | | |/ _ \ __| | | | '_ \
  # | |_\ \ | |_| |  __/ |_| |_| | | | |
  #  \____/_|\__,_|\___|\__|\__,_|_| |_|
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./appdata/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
    ports:
      - ${FIREWALL_VPN_INPUT_PORTS}:${FIREWALL_VPN_INPUT_PORTS}/tcp
      - ${FIREWALL_VPN_INPUT_PORTS}:${FIREWALL_VPN_INPUT_PORTS}/udp
      - 8080:8080       # qBittorrent Web UI
    restart: unless-stopped

  #       ______ _ _   _                            _
  #       | ___ (_) | | |                          | |
  #   __ _| |_/ /_| |_| |_ ___  _ __ _ __ ___ _ __ | |_
  #  / _` | ___ \ | __| __/ _ \| '__| '__/ _ \ '_ \| __|
  # | (_| | |_/ / | |_| || (_) | |  | | |  __/ | | | |_
  #  \__, \____/|_|\__|\__\___/|_|  |_|  \___|_| |_|\__|
  #     | |
  #     |_|
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS}
    volumes:
      - ./appdata/qbittorrent:/config
      - /mnt/hdd/data/torrents:/data/torrents
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gluetun
    network_mode: service:gluetun
    restart: unless-stopped

  #    ___      _ _        __ _
  #   |_  |    | | |      / _(_)
  #     | | ___| | |_   _| |_ _ _ __
  #     | |/ _ \ | | | | |  _| | '_ \
  # /\__/ /  __/ | | |_| | | | | | | |
  # \____/ \___|_|_|\__, |_| |_|_| |_|
  #                  __/ |
  #                 |___/
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5  #optional
    volumes:
      - ./appdata/jellyfin:/config
      - /mnt/hdd/data/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920       #optional
      - 7359:7359/udp   #optional
      - 1900:1900/udp   #optional
    restart: unless-stopped

